# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebdec4fab3cc1d9c0c8992096c6e7c76a16a208f4e472437badcbc8e3786ec039c0ff42c99c02d02cc30c822cf8ef608c2cd2a71b0b3505ded3338d89b3b2676

test:
  secret_key_base: bc3322976e3fd1f06b9bd04d273f58badfd1deaa71e3b13fbca93596280cb4fb85fa308115a8f469d1952519b7d28f2482c2258cf6d6f232a1fcf50490ed130c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
